name: Workflow 4 - Run Unit Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build debug and preprod apks and run tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: --stacktrace -Dtrace :app:testDebugUnitTest :app:assembleDevDebug :app:assemblePreprodRelease
      env:
        TERM: dumb
