name: Workflow 7 - AWS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: AWS CLI v2
      id: generate_auth_token
      uses: imehedi/actions-awscli-v2@latest
      with:
          args: codeartifact get-authorization-token --domain faa-modules --query authorizationToken --output text
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"

    - name: Set env codeartifact auth token
      env:
        AUTH_TOKEN_SECRET: |
          ${{ steps.generate_auth_token.outputs.authorizationToken }} 
      run: echo "CODEARTIFACT_AUTH_TOKEN=$AUTH_TOKEN_SECRET" >> $GITHUB_ENV
      
    - name: Get env codeartifact auth token (doesnt work)
      run: |
        echo ${{ steps.generate_auth_token.outputs.authorizationToken }} 

    - name: Capture and set custom output (?)
      id: capture_and_set_output
      run: |
        # Capture the output
        auth_token_output=$(aws codeartifact get-authorization-token --domain test-modules --query authorizationToken --output text)
        
        # Set it as a workflow output
        echo "::set-output name=auth_token_output::$auth_token_output"
        
    - name: Display auth_token_output (?)
      run: |
        echo "Auth Token Output: ${{ steps.capture_and_set_output.outputs.auth_token_output }}"

    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'myKeystore.jks'
        fileDir: './myKeystore/'
        encodedString: ${{ secrets.KEYSTORE }}

    - name: Cat
      run: ls ./myKeystore
        
    - name: Upload keystore
      uses: actions/upload-artifact@v3
      with:
        path: ./myKeystore/myKeystore.jks #${{ steps.decode_keystore.outputs.filePath }}
      
